# Generated by Django 4.2.19 on 2025-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['published_date'], name='api_video_publish_1c02cf_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['likes_count'], name='api_video_likes_c_0c8200_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['view_count'], name='api_video_view_co_1b2ded_idx'),
        ),
    ]
