version: "3.8"

services:
  backend:
    build: ./backend
    container_name: go_neutral_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: go_neutral_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend