version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-go_neutral_db}
      - POSTGRES_USER=${DB_USER:-go_neutral_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-GoNeutral@123}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-go_neutral_user} -d ${DB_NAME:-go_neutral_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn go_neutral.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-go_neutral_db}
      - DB_USER=${DB_USER:-go_neutral_user}
      - DB_PASSWORD=${DB_PASSWORD:-GoNeutral@123}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:3000}

  celery_worker:
    build: .
    command: celery -A go_neutral worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-go_neutral_db}
      - DB_USER=${DB_USER:-go_neutral_user}
      - DB_PASSWORD=${DB_PASSWORD:-GoNeutral@123}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1

  celery_beat:
    build: .
    command: celery -A go_neutral beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-go_neutral_db}
      - DB_USER=${DB_USER:-go_neutral_user}
      - DB_PASSWORD=${DB_PASSWORD:-GoNeutral@123}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      
  # Optional: Include a frontend service if needed
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  #   environment:
  #     - VITE_API_URL=http://localhost:8000/api

volumes:
  postgres_data:
  redis_data:
  static_volume: